### ISSUE TITLE
@denvercrime hasn't posted any articles since September

### ISSUE THREAD

**Issue by freejoe76** [denverpost/social#1]
The corresponding display group is still updating. Petty, correct me if someone else handles this.

https://twitter.com/denvercrime

**Comment by danielpetty** [comment]
Handle should be:

https://twitter.com/denvercrime

I didn't know that account/website existed? I would think this is Sara Grant's stuff now.

**Comment by freejoe76** [comment]
I emailed Sara Grant about this last week.

**Comment by danielpetty** [comment]
This has been fixed and is now tweeting.

**Comment by freejoe76** [comment]
Thanks dude!
